#!/usr/bin/env node
// Claude Code hooks for this repo. Reads the hook payload on stdin.
//   pre-edit   : refuse edits to generated files (exit 2 = block, stderr shown to the agent)
//   post-edit  : after a Markdown edit, run the translation structure check and report
import { execSync } from "node:child_process";
import { relative, resolve } from "node:path";

const mode = process.argv[2];
const root = resolve(process.env.CLAUDE_PROJECT_DIR || process.cwd());
let raw = "";
process.stdin.on("data", (c) => (raw += c)).on("end", () => {
  let payload = {};
  try { payload = JSON.parse(raw); } catch {}
  const file = payload.tool_input?.file_path || payload.tool_input?.path || "";
  // Path relative to the project root, so a checkout named "agent-fundamentals" is not mistaken for the output folder.
  const rel = file ? relative(root, resolve(root, file)).split("\\").join("/") : "";

  if (mode === "pre-edit") {
    if (/^agent-fundamentals\//.test(rel) || rel === "claude-agent-fundamentals.html") {
      console.error(`Blocked: ${rel} is generated by build.mjs. Edit the Markdown or build.mjs, then run npm run build.`);
      process.exit(2);
    }
    return;
  }

  if (mode === "post-edit" && (rel === "claude-agent-fundamentals.md" || /^i18n\/[a-z]{2}\.md$/.test(rel))) {
    try {
      const out = execSync("npm run -s check", { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
      console.log(out.trim().split("\n").filter((l) => /OK:|MISMATCH/.test(l)).join("\n"));
    } catch (e) {
      console.log("Translation structure check FAILED after this edit:\n" + String(e.stdout || e.message).slice(-1500));
    }
  }
});
